Description: DynamoDB for NextPassword

Resources:
  User:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: DynamoDB
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'dynamodb:*'
                Resource:
                  - 'Fn::GetAtt':
                      - Table
                      - Arn
                  - 'Fn::Sub': '${Table.Arn}/*'

  Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE