Transform: AWS::Serverless-2016-10-31

Description: Python Lambda Layers

Outputs:
  ytdlp:
    Value: !Ref ytdlp
    Description: python lambda layer for ytdlp
    Export:
      Name: !Sub ${AWS::StackName}-ytdlp
  requests:
    Value: !Ref requests
    Description: python lambda layer for requests
    Export:
      Name: !Sub ${AWS::StackName}-requests
  ffmpeg:
    Value: !Ref ffmpeg
    Description: python lambda layer for ffmpeg
    Export:
      Name: !Sub ${AWS::StackName}-ffmpeg

Resources:
  ytdlp:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: yt-dlp
      CompatibleRuntimes:
        - python3.9
      Description: YouTube-DLP (Python)
      LayerName: yt-dlp
    Metadata:
      BuildMethod: python3.9

  requests:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: requests
      CompatibleRuntimes:
        - python3.9
      Description: requests (python)
      LayerName: requests
    Metadata:

  ffmpeg:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ffmpeg
      CompatibleRuntimes:
        - python3.9
      Description: ffmpeg (python)
      LayerName: ffmpeg
    Metadata:
      BuildMethod: python3.9