Transform: AWS::Serverless-2016-10-31

Description: python-spotify

Parameters:
  SpotifyClientId:
    Type: String

  SpotifyClientSecret:
    Type: String

  # Hard coding for now
  Api:
    Type: String

Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref AWS::StackName

  Authorization:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: code/authorization
      Environment:
        Variables:
          SpotifyClientId: !Ref SpotifyClientId
          SpotifyClientSecret: !Ref SpotifyClientSecret
          Table: !Ref Table
          RedirectUri: !Ref Api
      Timeout: 120
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        HttpEvent:
          Type: HttpApi
          Properties:
            Path: /auth
            Method: get

  GenerateUrl:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: code/generate-url
      Environment:
        Variables:
          SpotifyClientId: !Ref SpotifyClientId
          RedirectUri: !Ref Api
      Timeout: 120
      Policies:
        - AWSLambdaExecute
      Events:
        HttpEvent:
          Type: HttpApi
          Properties:
            Path: /generate-url
            Method: get

  RefreshToken:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      CodeUri: code/refresh-token
      Environment:
        Variables:
          SpotifyClientId: !Ref SpotifyClientId
      Timeout: 120
      Policies:
        - AWSLambdaExecute