name: 'Self-Hosted Runner'

on:
  push:
    branches: [ "**"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: 'Build'
    runs-on: self-hosted

    steps:
    - name: Example
      #if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: |
        shutdown
